### PR TITLE
Use state stores automatically

### PR DESCRIPTION
**Pull request by mathialo**

### CODE REVIEW

**Review by einarmo — APPROVED** [review]
Code looks good. Why do we want this change?

**Comment by mathialo** [comment]
When the time series upload queue actually makes an upload it would be nice to have the state store automatically update itself.

**Comment by einarmo** [comment]
What happens if the user sets use_default_state_store to False?

**Comment by mathialo** [comment]
Then a `NoStateStore` (just keeping states in memory, discarded when extractor is shut down) is initiated instead of a `LocalStateStore` (json file). So the `state_store` attribute is guaranteed to be set, and the interface outlined in `AbstractStateStore` can be used, but the load/save functions do nothing.

Actually, I think I have discovered a bug in the utils writing up this answer (we weren't loading local state store when needed), PR coming up there.

**Comment by einarmo** [comment]
So now the JSON state store is enabled by default? This is kind of a breaking change, isn't it?

**Comment by mathialo** [comment]
Seeing that this is still 0.x I wouldn't worry about breaking. But how would adding a default be breaking?

**Comment by einarmo** [comment]
It would be, I think, since it silently changes behavior, but yeah, I thought we were on the main utils...

**Comment by mathialo** [comment]
> silently changes behavior

I would rather phrase it as It brings the behavior to what the docs described. But let's move that discussion to https://github.com/cognitedata/python-extractor-utils/pull/130

**Pull request merged**
